### ISSUE TITLE
Where is your known_devices.yaml file, generated by nmap_tracker?

### ISSUE THREAD

**Issue by ricardoquecria** [DubhAd/Home-AssistantConfig#2]
Where is your known_devices.yaml file, generated by nmap_tracker?

**Comment by CCOSTAN** [comment]
typically, it is in the config directory.  The same directory as your COnfiguration.yaml.  Most people do not publish it in GitHub though since it is full of MAC addresses.

**Comment by ricardoquecria** [comment]
> typically, it is in the config directory. The same directory as your COnfiguration.yaml. Most people do not publish it in GitHub though since it is full of MAC addresses.

Yes Yes! But I saw in the documentation that this file is no longer needed.
